#+ summary: Retrieves information for a given country.
#+ description: Returns the information for the provided country
#+   in the EHRI-KG, including the following information&#58;
#+
#+     - IRI
#+
#+     - label
#+
#+     - archival history
#+
#+     - archival situation
#+
#+     - research extensive
#+
#+     - research summary
#+ tags:
#+   - countries


PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ehri:  <http://lod.ehri-project-test.eu/ontology#>

SELECT ?countryLabel ?archivalHistory ?archivalSituation ?researchExtensive ?researchSummary WHERE {
	?_country_iri a ehri:Country ;
        rico:name ?countryLabel .
    OPTIONAL { ?_country_iri ehri:archivalHistory ?archivalHistory . }
    OPTIONAL { ?_country_iri ehri:archivalSituation ?archivalSituation . }
    OPTIONAL { ?_country_iri ehri:researchExtensive ?researchExtensive . }
    OPTIONAL { ?_country_iri ehri:researchSummary ?researchSummary . }
   
}