#+ summary: Returns the total number of institution.
#+ tags:
#+   - institutions
#+   - mcp

PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ehri:  <http://lod.ehri-project-test.eu/ontology#>

SELECT (COUNT(?institution) AS ?totalInstitutions) WHERE {
	?institution a ehri:Institution .
}