#+ summary: Searches for institutions located in a given country. 
#+ description: Returns the IRI and the label for all the institutions located in the introduced country.
#+ tags:
#+   - institutions
#+   - mcp

PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ehri:  <http://lod.ehri-project-test.eu/ontology#>

SELECT ?institution ?institutionName WHERE {
	?country a ehri:Country ;
        rico:name ?countryLabel ;
        rico:isOrWasLocationOfAgent ?institution .
    ?institution a ehri:Institution ;
        rico:name ?institutionName .
    FILTER (LCASE(?countryLabel) = LCASE(?_countryName_en))
}