#+ summary: Searches information for a given country.
#+ description: Returns the information for the provided country
#+   in the EHRI-KG, including the following information&#58;
#+
#+     - IRI
#+
#+     - label
#+
#+     - archival history
#+
#+     - archival situation
#+
#+     - research extensive
#+
#+     - research summary
#+
#+     - EHRI Portal link  
#+ tags:
#+   - countries
#+   - mcp


PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ehri:  <http://lod.ehri-project-test.eu/ontology#>

SELECT ?country ?countryLabel ?archivalHistory ?archivalSituation ?researchExtensive ?researchSummary ?ehriPortalLink WHERE {
	?country a ehri:Country .
    ?country rico:name ?countryLabel .
    OPTIONAL { ?country ehri:archivalHistory ?archivalHistory . }
    OPTIONAL { ?country ehri:archivalSituation ?archivalSituation . }
    OPTIONAL { ?country ehri:researchExtensive ?researchExtensive . }
    OPTIONAL { ?country ehri:researchSummary ?researchSummary . }
    FILTER (LCASE(?countryLabel) = LCASE(?_countryName_en))
    BIND(IRI(REPLACE(STR(?country), "http://lod.ehri-project-test.eu/countries/", "https://portal.ehri-project.eu/countries/")) AS ?ehriPortalLink)   
}